# Use container-based distribution
sudo: false
language: c++
addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
      - boost-latest
    packages: &default_packages
      - libboost-program-options1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
matrix:
  include:
    - env: COMPILER=g++-5
      os: linux
      language: cpp
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - *default_packages
            - g++-5
    - env: COMPILER=g++-6
      os: linux
      language: cpp
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - *default_packages
            - g++-6
script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER=$COMPILER
  - make -j3 && make -j3 run-tests
