# Use container-based distribution
sudo: false
language: c++
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost-program-options1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
      env: COMPILER=g++-5
script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER=$COMPILER
  - make -j3 && make -j3 run-tests
