# Use container-based distribution
sudo: false
language: c++
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost1.55-all-dev
      env: COMPILER=g++-5
script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER=$COMPILER
  - make && make run-tests
